<div>
    <?php foreach ($messages as $message) : ?>
        <div class="alert alert-<?= $message['type'] ?>" role="alert">
            <?= $message['message'] ?>
        </div>
    <?php endforeach; ?>

    <div class="row align-items-start">
        <div class="col-1">
            <img src="../Pictures/profile.png" alt="Profile picture" class="table-border-custom img-fluid p-2" />
        </div>
        <div class="col-10 mx-4">
            <h3 class="h3">
                Pojištěnec <?= $insuredPerson['name'] ?>
            </h3>

            <div class="row my-2">
                <div class="col-4">
                    <?= $insuredPerson['address'] ?>
                </div>

                <div class="col-4">
                    <?= $insuredPerson['email'] ?>
                </div>
            </div>

            <div class="row my-3">
                <div class="col-4">
                    <?= $insuredPerson['city'] ?>
                </div>

                <div class="col-4">
                    <?= $insuredPerson['phone'] ?>
                </div>
            </div>

            <div class="row my-2">
                <div class="col-4">
                    <?= $insuredPerson['zip_code'] ?>
                </div>
            </div>
        </div>
    </div>

    <div>
        <h3 class="h3 my-5">
            Sjednaná pojištění
        </h3>

        <table class="table table-border-custom my-4">

            <thead class="fw-bold">
            <tr>
                <th>Pojištění</th>
                <th>Částka</th>
                <th></th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($insuranceList as $insurance) : ?>
                <tr>
                    <td class="fw-bold align-middle">
                        <a href="insuranceDetail/<?= $insurance['id'] ?>">
                            <?= $insurance['kind_of_insurance'] ?>
                        </a>
                    </td>

                    <td class="align-middle">
                        <?= $insurance['sum'] ?>
                    </td>

                    <td>
                        <div class="mx-3">

                            <a href="insuredPersonDetail/<?= $insuredPerson['id'] ?>?delete=<?= $insurance['id'] ?>"
                               class="btn btn-danger mx-2">
                                Odstranit
                            </a>

                            <a href="insuranceForm?idInsuredPerson=<?= $insuredPerson['id'] ?>&edit=<?= $insurance['id'] ?>"
                               class="btn btn-warning text-white">
                                Editovat
                            </a>

                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>

        </table>

        <div class="text-center">
            <a href="insuranceForm?idInsuredPerson=<?= $insuredPerson['id'] ?>"
               class="btn btn-primary btn-lg">
                Přidat pojištění
            </a>

            <a href="insuredPersonForm?edit=<?= $insuredPerson['id'] ?>"
               class="btn btn-warning text-white mx-2 btn-lg">
                Editovat pojištěnce
            </a>

            <a href="insuredPersonList?delete=<?= $insuredPerson['id'] ?>"
               class="btn btn-danger btn-lg">
                Odstranit pojištěnce
            </a>
        </div>
    </div>
</div>