<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localproject" />
        <meta charset="UTF-8" />
        <title><?= $title ?></title>
        <meta name="description" content="<?= $description ?>" />
        <meta name="keywords" content="<?= $keyWords ?>" />
        <link rel="stylesheet" href="style.css" type="text/css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>

    <body class="d-flex flex-column min-vh-100">

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark nav-menu">
            <div class="navbar-brand mx-4">PojištěníApp</div>

            <div class="d-flex justify-content-between w-100">
                <ul class="navbar-nav mx-4">
                    <li class="nav-item mx-3">
                        <a href="insuredPersonList" class="nav-link">Pojištěnci</a>
                    </li>

                    <li class="nav-item mx-3">
                        <a href="#" class="nav-link">O aplikaci...</a>
                    </li>
                </ul>

                <ul class="navbar-nav mx-4">
                    <?php if ($user): ?>
                        <li class="nav-item mx-3">
                            <a href="administration" class="nav-link">Administrace účtu</a>
                        </li>
                    <?php endif; ?>

                    <?php if (!$user): ?>
                        <li class="nav-item mx-3">
                            <a href="registration" class="nav-link">Registration</a>
                        </li>
                    <?php endif; ?>

                    <?php if (!$user): ?>
                        <li class="nav-item mx-3">
                            <a href="login" class="nav-link">Přihlášení</a>
                        </li>
                    <?php endif; ?>

                    <?php if ($user): ?>
                        <li class="nav-item mx-3">
                            <a href="administration/logout" class="nav-link">Odhlásit se</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </nav>
    </header>

    <article class="flex-grow-1">
        <?php $this->controller->writeView(); ?>
    </article>

    <footer>
        <div class="d-flex justify-content-center">
            Stránka pro evidenci pojištěných vytvořena Danielem Vraspírem
            k projektu pro&nbsp;<a href="https://www.itnetwork.cz/">itnetwork</a>.
        </div>
    </footer>

    </body>
</html>