<h1>Registration</h1>

<?php foreach ($messages as $message) : ?>
    <div class="alert alert-<?= $message['type'] ?>" role="alert">
        <?= $message['message'] ?>
    </div>
<?php endforeach; ?>

<div class="container-fluid my-5">
    <form method="post">
        <div class="row align-items-center">
            <div class="col-12">
                <div class="col-4">
                    <label class="form-label" for="name">
                        Jméno
                    </label>
                    <input type="text" name="name" class="form-control" id="name" />
                </div>

                <div class="col-4">
                    <label class="form-label" for="password">
                        Heslo
                    </label>
                    <input type="password" name="password" class="form-control" id="password" />
                </div>

                <div class="col-4">
                    <label class="form-label" for="password_repeat">
                        Heslo znovu
                    </label>
                    <input type="password" name="password_repeat" class="form-control" id="password_repeat" />
                </div>

                <div class="col-4">
                    <label class="form-label" for="year">
                        Zadej aktuální rok (antispam)
                    </label>
                    <input type="text" name="year" class="form-control" id="year" />
                </div>

                <div class="mt-3">
                    <button type="submit" class="btn btn-primary col-1">
                        Registrovat
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>